# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  camiseta.com:
    site_hosts:
    - canonical: camiseta.test
      redirects:
      - www.camiseta.test
    local_path: ../site
    admin_email: admin@camiseta.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
