# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  camiseta.com:
    site_hosts:
    - canonical: staging.camisetaecoisaseria.com.br
      #redirects:
      #- www.staging.camisetaecoisaseria.com.br
    local_path: ../site
    branch: master
    repo: git@github.com:dsemblano/camisetaecoisaseria.com.br.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
